# Generated by Django 5.0.1 on 2024-03-31 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesource', '0003_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='category',
        ),
    ]
