# Generated by Django 5.0.1 on 2024-04-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesource', '0006_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='tittle',
        ),
    ]
