# Generated by Django 5.0.1 on 2024-04-04 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesource', '0007_rename_title_post_tittle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tittle',
            new_name='title',
        ),
    ]
