# Generated by Django 5.0.1 on 2024-04-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesource', '0008_rename_tittle_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(max_length=255),
        ),
    ]
