# Generated by Django 5.0.1 on 2024-04-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesource', '0009_alter_post_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
