# Generated by Django 5.0.1 on 2024-04-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesource', '0011_slider_path_slider_text_slider_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
