# Generated by Django 5.0.1 on 2024-04-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesource', '0013_alter_post_image_alter_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='BASE_DIR/sitesource/temp/images'),
        ),
    ]
