# Generated by Django 5.0.1 on 2024-04-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesource', '0015_yemeks_alter_post_image_alter_post_writer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='text',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
