# Generated by Django 5.0.1 on 2024-04-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesource', '0016_alter_slider_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
